import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import {
  AlertTriangle,
  ArrowRight,
  Brain,
  CalendarClock,
  CheckCircle,
  Headphones,
  Loader2,
  Mail,
  RefreshCw,
  Send,
  ShieldAlert,
  Sparkles,
  TrendingUp,
} from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import {
  AI_TEMPLATES,
  answerTemplate,
  ApcmAiDigest,
  DigestItem,
  getDigest,
  requestDigestRefresh,
  TemplateAnswer,
} from '@/services/apcmAiService';
import { ApcmAiActionBoard, ApcmAiAction } from '@/components/ApcmAiActionBoard';

// Demo: curated priority actions. In ty these are computed from the live signals
// (stalled hot leads, coaching scores, objection handling, callbacks, instructions).
const PRIORITY_ACTIONS: ApcmAiAction[] = [
  { severity: 'high', icon: 'flame', title: '5 hot leads stalled 7+ days', detail: 'Qualified, hot leads with no contact this week — instructions slipping away. Work them before they go cold.', cta: 'Open stalled hot leads', href: '/lead-management?pulse=stalled' },
  { severity: 'high', icon: 'coaching', title: 'James Okoro dropped to a 50 coaching score', detail: 'Needs coaching: 12h speed-to-lead and weak objection handling. Listen to a couple of his calls today.', cta: 'Open his calls', href: '/call-analysis' },
  { severity: 'med', icon: 'objection', title: 'Comparing Quotes handled well only 25%', detail: '28 calls this week, our worst-handled objection. Run a quick huddle on value framing versus price.', cta: 'See the exchanges', href: '/call-analysis' },
  { severity: 'med', icon: 'callback', title: '69 callbacks overdue, 59 over 3 days', detail: 'Promised callbacks are slipping. Each missed one risks a lost instruction; clear the oldest first.', cta: 'Open the diary', href: '/diary' },
  { severity: 'med', icon: 'flame', title: '27 leads quoted with no follow-up', detail: 'Quotes sent but untouched since. A nudge now lifts conversion; prioritise the highest-value ones.', cta: 'Open quoted leads', href: '/lead-management?pulse=quoted-no-touch' },
  { severity: 'low', icon: 'win', title: '17 instructions confirmed yesterday', detail: 'Louise led with 8 and a +0.34 client sentiment. £4,250 in deposits landed — momentum is up.', cta: 'View the pipeline', href: '/pipeline-pulse' },
];

const toneDot: Record<string, string> = {
  good: 'bg-green-500',
  bad: 'bg-red-500',
  warn: 'bg-amber-500',
  info: 'bg-navy-400',
};

const DigestItemRow: React.FC<{ item: DigestItem }> = ({ item }) => (
  <div className="flex items-start gap-2.5">
    <span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${toneDot[item.tone] || toneDot.info}`} />
    <p className="text-sm leading-6 text-gray-700">{item.text}</p>
  </div>
);

interface ChatMessage {
  id: number;
  role: 'user' | 'ai';
  text?: string;
  answer?: TemplateAnswer;
  thinking?: boolean;
}

export const ApcmAi: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { user } = useAuth();
  const [digest, setDigest] = useState<ApcmAiDigest | null>(null);
  const [isLoadingDigest, setIsLoadingDigest] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [refreshNote, setRefreshNote] = useState<string | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [freeText, setFreeText] = useState('');
  const [isAnswering, setIsAnswering] = useState(false);
  const messageIdRef = useRef(0);
  const chatEndRef = useRef<HTMLDivElement | null>(null);

  const loadDigest = async () => {
    setIsLoadingDigest(true);
    try {
      setDigest(await getDigest());
    } catch (digestError) {
      console.error('Error loading APCM AI digest:', digestError);
      setDigest(null);
    } finally {
      setIsLoadingDigest(false);
    }
  };

  useEffect(() => {
    loadDigest();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Deep link from the floating assistant: /apcm-ai?ask=<templateId>
  const askedFromUrlRef = useRef(false);
  useEffect(() => {
    if (askedFromUrlRef.current) return;
    const ask = searchParams.get('ask');
    const template = AI_TEMPLATES.find((candidate) => candidate.id === ask);
    if (template) {
      askedFromUrlRef.current = true;
      askTemplate(template.id, template.question);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchParams]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' });
  }, [messages]);

  const handleRefreshDigest = async () => {
    setIsRefreshing(true);
    setRefreshNote(null);
    const result = await requestDigestRefresh();
    if (result.ok) {
      await loadDigest();
      setRefreshNote('Fresh digest generated by APCM AI.');
    } else {
      // Edge function not deployed yet — recompute from live data instead.
      await loadDigest();
      setRefreshNote('Refreshed from live CRM data. (The overnight AI digest service takes over once deployed.)');
    }
    setIsRefreshing(false);
  };

  const askTemplate = async (templateId: string, question: string) => {
    if (isAnswering) return;
    const userId = ++messageIdRef.current;
    const thinkingId = ++messageIdRef.current;
    setMessages((current) => [
      ...current,
      { id: userId, role: 'user', text: question },
      { id: thinkingId, role: 'ai', thinking: true },
    ]);
    setIsAnswering(true);

    try {
      const answer = await answerTemplate(templateId);
      setMessages((current) => current.map((message) =>
        message.id === thinkingId ? { id: thinkingId, role: 'ai', answer } : message
      ));
    } catch (answerError) {
      console.error('APCM AI template error:', answerError);
      setMessages((current) => current.map((message) =>
        message.id === thinkingId
          ? { id: thinkingId, role: 'ai', answer: { paragraphs: ['Something went wrong reading the data — try again in a moment.'] } }
          : message
      ));
    } finally {
      setIsAnswering(false);
    }
  };

  const handleFreeText = async (event: React.FormEvent) => {
    event.preventDefault();
    const text = freeText.trim();
    if (!text || isAnswering) return;
    setFreeText('');

    // v1: match free text against the known templates; full free-form Q&A is v2.
    const lower = text.toLowerCase();
    const matched = AI_TEMPLATES.find((template) => {
      const keywords: Record<string, string[]> = {
        digest: ['digest', 'summary', 'today', 'happening'],
        bestAgent: ['best agent', 'top agent', 'who did well', 'best on calls'],
        agentIssues: ['agent issue', 'agent problem', 'struggl', 'underperform'],
        droppage: ['droppage', 'dropping', 'losing leads', 'lost leads', 'objection'],
        fakeLeads: ['fake', 'spam lead', 'duplicate lead'],
        instructions: ['instruction'],
        spam: ['email', 'spam'],
      };
      return (keywords[template.id] || []).some((keyword) => lower.includes(keyword));
    });

    if (matched) {
      await askTemplate(matched.id, text);
      return;
    }

    const userId = ++messageIdRef.current;
    const aiId = ++messageIdRef.current;
    setMessages((current) => [
      ...current,
      { id: userId, role: 'user', text },
      {
        id: aiId,
        role: 'ai',
        answer: {
          paragraphs: ['I can answer the suggested questions below for now — free-form questions arrive in the next APCM AI version.'],
          footnote: 'v1 preview',
        },
      },
    ]);
  };

  const plannedSchedules = useMemo(() => ([
    { name: 'Morning digest to managers', detail: 'Email + CRM, daily 07:30', icon: Mail },
    { name: 'Weekly agent scorecard', detail: 'Email, Mondays 08:00', icon: TrendingUp },
    { name: 'Hot-call instant alert', detail: 'SMS to duty manager, live', icon: AlertTriangle },
    { name: 'Deliverability warning', detail: 'When spam rate spikes', icon: ShieldAlert },
  ]), []);

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <div className="flex flex-wrap items-center gap-3">
            <span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-navy-950 text-white">
              <Brain className="h-5 w-5" />
            </span>
            <h1 className="text-2xl font-bold text-gray-900">APCM AI</h1>
            <span className="rounded-full bg-purple-100 px-2.5 py-1 text-xs font-semibold text-purple-700">v1 preview</span>
          </div>
          <p className="mt-1 text-sm text-gray-600">
            Your business at a glance — what happened, what needs you, and what to do next. No digging required.
          </p>
        </div>
        <button
          type="button"
          onClick={handleRefreshDigest}
          disabled={isRefreshing}
          className="btn-primary inline-flex items-center gap-2 self-start text-sm disabled:opacity-60"
        >
          {isRefreshing ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
          Refresh digest
        </button>
      </div>

      {refreshNote && (
        <div className="rounded-md border border-blue-200 bg-blue-50 px-4 py-2.5 text-sm text-blue-900">{refreshNote}</div>
      )}

      <ApcmAiActionBoard actions={PRIORITY_ACTIONS} onAction={(href) => navigate(href)} />

      {/* Digest hero */}
      <div className="rounded-xl border border-gray-200 bg-white shadow-sm">
        <div className="border-b border-gray-100 bg-gradient-to-r from-navy-950 to-navy-800 px-6 py-5 text-white">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-white/60">
            <Sparkles className="h-3.5 w-3.5" />
            Daily digest{digest ? ` · ${digest.digestDate}` : ''}
            {digest?.generatedBy === 'live-data' && (
              <span className="rounded-full bg-white/10 px-2 py-0.5 normal-case tracking-normal">live data</span>
            )}
          </div>
          <h2 className="mt-2 text-xl font-semibold leading-7">
            {isLoadingDigest ? 'Reading your business...' : digest?.headline || 'No digest available yet.'}
          </h2>
        </div>

        {isLoadingDigest ? (
          <div className="flex min-h-[160px] items-center justify-center text-gray-500">
            <Loader2 className="mr-2 h-5 w-5 animate-spin" />
            Building your digest from CRM data...
          </div>
        ) : digest ? (
          <div className="grid gap-6 p-6 lg:grid-cols-3">
            {digest.sections.map((section) => (
              <div key={section.title}>
                <h3 className="text-xs font-semibold uppercase tracking-wide text-gray-500">{section.title}</h3>
                <div className="mt-3 space-y-2.5">
                  {section.items.map((item, index) => (
                    <DigestItemRow key={`${section.title}-${index}`} item={item} />
                  ))}
                </div>
              </div>
            ))}
            {digest.advice.length > 0 && (
              <div className={digest.sections.length >= 3 ? 'lg:col-span-3' : ''}>
                <h3 className="text-xs font-semibold uppercase tracking-wide text-gray-500">APCM AI suggests</h3>
                <div className="mt-3 grid gap-2.5 lg:grid-cols-2">
                  {digest.advice.map((item, index) => (
                    <div key={`advice-${index}`} className="rounded-lg bg-gray-50 p-3">
                      <DigestItemRow item={item} />
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="p-6 text-sm text-gray-500">
            No digest yet — data appears after the nightly call import has run.
          </div>
        )}
      </div>

      <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]">
        {/* Ask APCM AI */}
        <div className="flex flex-col rounded-xl border border-gray-200 bg-white shadow-sm">
          <div className="border-b border-gray-100 px-5 py-4">
            <h2 className="text-base font-semibold text-gray-900">Ask APCM AI</h2>
            <p className="text-sm text-gray-500">Click a question — answers come straight from your CRM data.</p>
          </div>

          <div className="max-h-[440px] min-h-[220px] flex-1 space-y-4 overflow-y-auto px-5 py-4">
            {messages.length === 0 && (
              <div className="flex h-full min-h-[180px] flex-col items-center justify-center text-center">
                <Brain className="h-10 w-10 text-gray-200" />
                <p className="mt-3 max-w-sm text-sm text-gray-500">
                  Try "{AI_TEMPLATES[0].question}" — or any question below.
                </p>
              </div>
            )}
            {messages.map((message) => (
              <div key={message.id} className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                {message.role === 'user' ? (
                  <div className="max-w-[85%] rounded-2xl rounded-br-sm bg-navy-950 px-4 py-2.5 text-sm text-white">
                    {message.text}
                  </div>
                ) : (
                  <div className="flex max-w-[90%] items-start gap-2.5">
                    <span className="mt-0.5 inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-navy-950 text-white">
                      <Brain className="h-3.5 w-3.5" />
                    </span>
                    <div className="rounded-2xl rounded-tl-sm bg-gray-50 px-4 py-3">
                      {message.thinking ? (
                        <div className="flex items-center gap-2 text-sm text-gray-500">
                          <Loader2 className="h-4 w-4 animate-spin" />
                          Reading your CRM data...
                        </div>
                      ) : (
                        <div className="space-y-2.5">
                          {message.answer?.paragraphs.map((paragraph, index) => (
                            <p key={index} className="text-sm leading-6 text-gray-800">{paragraph}</p>
                          ))}
                          {message.answer?.items && message.answer.items.length > 0 && (
                            <div className="space-y-2 pt-1">
                              {message.answer.items.map((item, index) => (
                                <DigestItemRow key={index} item={item} />
                              ))}
                            </div>
                          )}
                          {message.answer?.footnote && (
                            <p className="pt-1 text-xs text-gray-400">{message.answer.footnote}</p>
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            ))}
            <div ref={chatEndRef} />
          </div>

          <div className="border-t border-gray-100 px-5 py-4">
            <div className="flex flex-wrap gap-1.5">
              {AI_TEMPLATES.map((template) => (
                <button
                  key={template.id}
                  type="button"
                  onClick={() => askTemplate(template.id, template.question)}
                  disabled={isAnswering}
                  title={template.source}
                  className={`rounded-full border px-3 py-1.5 text-xs font-medium transition disabled:opacity-50 ${
                    template.planned
                      ? 'border-dashed border-gray-300 text-gray-500 hover:border-gray-400'
                      : 'border-gray-200 bg-white text-gray-700 hover:border-navy-950 hover:text-navy-950'
                  }`}
                >
                  {template.question}
                </button>
              ))}
            </div>
            <form onSubmit={handleFreeText} className="mt-3 flex items-center gap-2">
              <input
                type="text"
                value={freeText}
                onChange={(event) => setFreeText(event.target.value)}
                placeholder="Ask anything about your business... (v1 answers the questions above)"
                className="input-field text-sm"
              />
              <button
                type="submit"
                disabled={!freeText.trim() || isAnswering}
                className="btn-primary inline-flex h-10 w-10 shrink-0 items-center justify-center !p-0 disabled:opacity-50"
                title="Send"
              >
                <Send className="h-4 w-4" />
              </button>
            </form>
          </div>
        </div>

        {/* Modules column */}
        <div className="space-y-5">
          {/* Scheduled communications — interface preview */}
          <div className="rounded-xl border border-gray-200 bg-white shadow-sm">
            <div className="flex items-start justify-between border-b border-gray-100 px-5 py-4">
              <div>
                <h2 className="flex items-center gap-2 text-base font-semibold text-gray-900">
                  <CalendarClock className="h-4 w-4 text-navy-950" />
                  Scheduled communications
                </h2>
                <p className="mt-0.5 text-sm text-gray-500">APCM AI sends these automatically.</p>
              </div>
              <span className="rounded-full bg-purple-100 px-2.5 py-1 text-xs font-semibold text-purple-700">Preview</span>
            </div>
            <div className="divide-y divide-gray-50 px-5">
              {plannedSchedules.map((schedule) => {
                const Icon = schedule.icon;
                return (
                  <div key={schedule.name} className="flex items-center justify-between gap-3 py-3.5">
                    <div className="flex items-start gap-3">
                      <span className="mt-0.5 inline-flex h-8 w-8 items-center justify-center rounded-lg bg-gray-100 text-gray-500">
                        <Icon className="h-4 w-4" />
                      </span>
                      <div>
                        <p className="text-sm font-medium text-gray-900">{schedule.name}</p>
                        <p className="text-xs text-gray-500">{schedule.detail}</p>
                      </div>
                    </div>
                    <button
                      type="button"
                      disabled
                      title="Coming in APCM AI v2"
                      className="relative h-6 w-11 shrink-0 cursor-not-allowed rounded-full bg-gray-200"
                    >
                      <span className="absolute left-0.5 top-0.5 h-5 w-5 rounded-full bg-white shadow" />
                    </button>
                  </div>
                );
              })}
            </div>
            <p className="border-t border-gray-100 px-5 py-3 text-xs text-gray-400">
              Interface preview — switching these on arrives in APCM AI v2.
            </p>
          </div>

          {/* Quick paths */}
          <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
            <h2 className="text-base font-semibold text-gray-900">Dig deeper</h2>
            <p className="mt-0.5 text-sm text-gray-500">When the digest flags something, go straight to the detail.</p>
            <div className="mt-4 space-y-2">
              <button
                type="button"
                onClick={() => navigate('/call-analysis')}
                className="flex w-full items-center justify-between rounded-lg border border-gray-200 px-4 py-3 text-left text-sm font-medium text-gray-900 hover:border-navy-950"
              >
                <span className="flex items-center gap-2"><Headphones className="h-4 w-4 text-navy-950" /> Call Analysis — call by call</span>
                <ArrowRight className="h-4 w-4 text-gray-400" />
              </button>
              <button
                type="button"
                onClick={() => navigate('/reports/instructions')}
                className="flex w-full items-center justify-between rounded-lg border border-gray-200 px-4 py-3 text-left text-sm font-medium text-gray-900 hover:border-navy-950"
              >
                <span className="flex items-center gap-2"><CheckCircle className="h-4 w-4 text-green-600" /> Instructions report</span>
                <ArrowRight className="h-4 w-4 text-gray-400" />
              </button>
              <button
                type="button"
                onClick={() => navigate('/lead-time-tracking')}
                className="flex w-full items-center justify-between rounded-lg border border-gray-200 px-4 py-3 text-left text-sm font-medium text-gray-900 hover:border-navy-950"
              >
                <span className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-teal-600" /> Lead time tracking</span>
                <ArrowRight className="h-4 w-4 text-gray-400" />
              </button>
            </div>
          </div>

          {/* Roadmap */}
          <div className="rounded-xl border border-dashed border-gray-300 bg-gray-50/60 p-5">
            <h2 className="text-sm font-semibold text-gray-700">Coming next in APCM AI</h2>
            <ul className="mt-3 space-y-2 text-sm text-gray-500">
              <li>· Free-form questions over all CRM data</li>
              <li>· Email deliverability — spam and bounce tracking per day</li>
              <li>· Fake-lead radar with paid-click and behaviour checks</li>
              <li>· Automatic morning digest by email and SMS alerts</li>
              <li>· Weekly coaching notes per agent, written by AI</li>
            </ul>
            {user?.role === 'Admin' && (
              <p className="mt-3 text-xs text-gray-400">Powered by the same OpenAI connection as APCM call intelligence.</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ApcmAi;
