import React, { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import { searchLeadOptions, updateLead, LeadOption } from '@/services/leadsService';
import { createTask } from '@/services/tasksService';
import { supabase } from '@/lib/supabase';
import { 
  Calendar, 
  Clock, 
  Phone, 
  Mail, 
  MessageSquare, 
  CheckCircle, 
  AlertCircle,
  Plus,
  Search,
  User,
  Target,
  Play,
  Archive,
  Edit,
  X,
  Loader2
} from 'lucide-react';

interface DiaryTask {
  id: string;
  leadId: string;
  leadName: string;
  leadPhone: string;
  leadEmail: string;
  taskType: 'Call' | 'SMS' | 'Email' | 'Follow-up' | 'Quote' | 'Payment';
  title: string;
  description: string;
  scheduledAt: string;
  dueAt: string;
  status: 'Scheduled' | 'In Progress' | 'Completed' | 'Overdue' | 'Cancelled';
  priority: 'High' | 'Medium' | 'Low';
  agentId: string;
  agentName: string;
  outcomeCode?: string;
  attemptNumber: number;
  maxAttempts: number;
  businessHours: boolean;
  autoGenerated: boolean;
  createdAt: string;
  completedAt?: string;
  notes?: string;
}

export const Diary: React.FC = () => {
  const { user } = useAuth();
  const [searchParams] = useSearchParams();
  const [filterStatus, setFilterStatus] = useState('All');
  const [filterType, setFilterType] = useState('All');
  const [filterAgent, setFilterAgent] = useState('All');
  const [searchTerm, setSearchTerm] = useState('');
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [selectedTask, setSelectedTask] = useState<DiaryTask | null>(null);
  const [leads, setLeads] = useState<LeadOption[]>([]);
  const [selectedLeadOption, setSelectedLeadOption] = useState<LeadOption | null>(null);
  const [agents, setAgents] = useState<Array<{ id: string; name: string; role: string }>>([]);
  const [isLoadingLeads, setIsLoadingLeads] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [leadSearchTerm, setLeadSearchTerm] = useState('');
  const [debouncedLeadSearchTerm, setDebouncedLeadSearchTerm] = useState('');
  const [showLeadDropdown, setShowLeadDropdown] = useState(false);

  // Debounce lead search term
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedLeadSearchTerm(leadSearchTerm);
    }, 450);

    return () => clearTimeout(timer);
  }, [leadSearchTerm]);

  const filteredLeads = leads;
  const [newTask, setNewTask] = useState({
    leadId: '',
    taskType: 'Call' as 'Call' | 'SMS' | 'Email' | 'Follow-up' | 'Quote' | 'Payment',
    title: '',
    description: '',
    scheduledAt: '',
    dueAt: '',
    priority: 'Medium' as 'High' | 'Medium' | 'Low',
    agentId: '',
    notes: ''
  });
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null);

  useEffect(() => {
    if (!toast) return;
    const timer = setTimeout(() => setToast(null), 4000);
    return () => clearTimeout(timer);
  }, [toast]);

  // Fetch lightweight lead options for task creation
  useEffect(() => {
    const loadLeads = async () => {
      if (!showCreateModal) {
        // Reset when modal closes
        setLeads([]);
        setLeadSearchTerm('');
        setSelectedLeadOption(null);
        setShowLeadDropdown(false);
        return;
      }
      
      if (!user) {
        console.warn('User not available, cannot load leads');
        return;
      }
      
      setIsLoadingLeads(true);
      try {
        const fetchedLeads = await searchLeadOptions({
          search: debouncedLeadSearchTerm,
          limit: 50,
          activeOnly: true,
          userId: user.role === 'Agent' ? user.id : undefined,
        });
        setLeads(fetchedLeads);
        // Auto-open dropdown if leads are available
        if (fetchedLeads.length > 0) {
          setShowLeadDropdown(true);
        }
      } catch (err) {
        console.error('Error loading leads:', err);
        setLeads([]);
      } finally {
        setIsLoadingLeads(false);
      }
    };
    
    if (showCreateModal && user) {
      loadLeads();
    }
  }, [showCreateModal, user, debouncedLeadSearchTerm]);

  // Fetch agents
  useEffect(() => {
    const loadAgents = async () => {
      try {
        const { data, error } = await supabase
          .from('users')
          .select('id, name, role')
          .in('role', ['Agent', 'Manager', 'Admin'])
          .order('name', { ascending: true });

        if (error) {
          console.error('Error loading agents:', error);
        } else {
          setAgents(data || []);
        }
      } catch (err) {
        console.error('Error loading agents:', err);
      }
    };

    loadAgents();
  }, []);

  // Handle URL parameters for actions
  useEffect(() => {
    const action = searchParams.get('action');
    if (action === 'schedule') {
      setShowCreateModal(true);
    }
  }, [searchParams]);

  // Mock data - replace with actual API calls
  const diaryTasks: DiaryTask[] = [
    {
      id: 'DT-001',
      leadId: 'L-001',
      leadName: 'John Smith',
      leadPhone: '+44 1704 773288',
      leadEmail: 'john.smith@email.com',
      taskType: 'Call',
      title: 'Initial Contact Call',
      description: 'First contact attempt for new lead',
      scheduledAt: '2024-01-15T09:00:00Z',
      dueAt: '2024-01-15T17:00:00Z',
      status: 'Scheduled',
      priority: 'High',
      agentId: 'agent1',
      agentName: 'Agent 1',
      outcomeCode: 'OC-001',
      attemptNumber: 1,
      maxAttempts: 5,
      businessHours: true,
      autoGenerated: true,
      createdAt: '2024-01-15T08:30:00Z'
    },
    {
      id: 'DT-002',
      leadId: 'L-002',
      leadName: 'Sarah Johnson',
      leadPhone: '+44 1704 773289',
      leadEmail: 'sarah.j@email.com',
      taskType: 'SMS',
      title: 'Follow-up SMS',
      description: 'Send SMS after no answer on call',
      scheduledAt: '2024-01-15T10:30:00Z',
      dueAt: '2024-01-15T18:00:00Z',
      status: 'Completed',
      priority: 'Medium',
      agentId: 'agent2',
      agentName: 'Agent 2',
      outcomeCode: 'OC-001',
      attemptNumber: 2,
      maxAttempts: 5,
      businessHours: true,
      autoGenerated: true,
      createdAt: '2024-01-15T09:15:00Z',
      completedAt: '2024-01-15T10:35:00Z',
      notes: 'SMS sent successfully, no reply received'
    },
    {
      id: 'DT-003',
      leadId: 'L-003',
      leadName: 'Mike Wilson',
      leadPhone: '+44 1704 773290',
      leadEmail: 'mike.w@email.com',
      taskType: 'Email',
      title: 'Quote Follow-up Email',
      description: 'Send follow-up email for quote sent 3 days ago',
      scheduledAt: '2024-01-15T11:00:00Z',
      dueAt: '2024-01-15T17:00:00Z',
      status: 'In Progress',
      priority: 'High',
      agentId: 'agent1',
      agentName: 'Agent 1',
      outcomeCode: 'OC-004',
      attemptNumber: 1,
      maxAttempts: 3,
      businessHours: true,
      autoGenerated: true,
      createdAt: '2024-01-15T10:45:00Z'
    },
    {
      id: 'DT-004',
      leadId: 'L-004',
      leadName: 'Emma Davis',
      leadPhone: '+44 1704 773291',
      leadEmail: 'emma.d@email.com',
      taskType: 'Call',
      title: 'Final Attempt Call',
      description: 'Final call attempt (5/5) before archiving',
      scheduledAt: '2024-01-15T14:00:00Z',
      dueAt: '2024-01-15T17:00:00Z',
      status: 'Overdue',
      priority: 'High',
      agentId: 'agent3',
      agentName: 'Agent 3',
      outcomeCode: 'OC-006',
      attemptNumber: 5,
      maxAttempts: 5,
      businessHours: true,
      autoGenerated: true,
      createdAt: '2024-01-15T13:30:00Z'
    },
    {
      id: 'DT-005',
      leadId: 'L-001',
      leadName: 'John Smith',
      leadPhone: '+44 1704 773288',
      leadEmail: 'john.smith@email.com',
      taskType: 'Quote',
      title: 'Prepare Quote',
      description: 'Create quote for interested lead',
      scheduledAt: '2024-01-16T09:00:00Z',
      dueAt: '2024-01-16T17:00:00Z',
      status: 'Scheduled',
      priority: 'Medium',
      agentId: 'agent1',
      agentName: 'Agent 1',
      outcomeCode: 'OC-002',
      attemptNumber: 0,
      maxAttempts: 0,
      businessHours: true,
      autoGenerated: false,
      createdAt: '2024-01-15T16:00:00Z'
    }
  ];

  const filteredTasks = diaryTasks.filter(task => {
    const matchesSearch = task.leadName.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         task.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         task.description.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = filterStatus === 'All' || task.status === filterStatus;
    const matchesType = filterType === 'All' || task.taskType === filterType;
    const matchesAgent = filterAgent === 'All' || task.agentId === filterAgent;
    
    return matchesSearch && matchesStatus && matchesType && matchesAgent;
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Scheduled': return 'bg-blue-100 text-blue-800';
      case 'In Progress': return 'bg-yellow-100 text-yellow-800';
      case 'Completed': return 'bg-green-100 text-green-800';
      case 'Overdue': return 'bg-red-100 text-red-800';
      case 'Cancelled': return 'bg-gray-100 text-gray-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'High': return 'bg-red-100 text-red-800';
      case 'Medium': return 'bg-yellow-100 text-yellow-800';
      case 'Low': return 'bg-green-100 text-green-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'Call': return <Phone className="h-4 w-4" />;
      case 'SMS': return <MessageSquare className="h-4 w-4" />;
      case 'Email': return <Mail className="h-4 w-4" />;
      case 'Follow-up': return <Clock className="h-4 w-4" />;
      case 'Quote': return <Target className="h-4 w-4" />;
      case 'Payment': return <CheckCircle className="h-4 w-4" />;
      default: return <AlertCircle className="h-4 w-4" />;
    }
  };

  const handleStartTask = (task: DiaryTask) => {
    console.log('Start task:', task.id);
    setSelectedTask(task);
  };

  const handleCompleteTask = (task: DiaryTask) => {
    console.log('Complete task:', task.id);
  };

  const handleRescheduleTask = (task: DiaryTask) => {
    console.log('Reschedule task:', task.id);
  };

  const handleCancelTask = (task: DiaryTask) => {
    console.log('Cancel task:', task.id);
  };

  const handleEditTask = (task: DiaryTask) => {
    setSelectedTask(task);
    setShowEditModal(true);
  };

  const handleDeleteTask = (task: DiaryTask) => {
    setSelectedTask(task);
    setShowDeleteModal(true);
  };

  const handleSaveTask = async () => {
    if (!newTask.leadId || !newTask.title) {
      alert('Please select a lead and enter a task title');
      return;
    }

    setIsSaving(true);
    try {
      const selectedLead = selectedLeadOption || leads.find(l => l.id === newTask.leadId);
      if (!selectedLead) {
        alert('Selected lead not found');
        return;
      }

      // Parse scheduled date/time
      const scheduledDate = newTask.scheduledAt ? new Date(newTask.scheduledAt) : new Date();
      const dueDate = newTask.dueAt ? new Date(newTask.dueAt) : scheduledDate;
      
      // Format dates for database (YYYY-MM-DD)
      const dueDateStr = dueDate.toISOString().split('T')[0];
      const dueTimeStr = dueDate.toTimeString().slice(0, 5); // HH:MM format

      // Determine assignedTo - use agentId if provided, otherwise use lead's assignedTo or current user
      const assignedTo = newTask.agentId || selectedLead.assignedTo || user?.id || '';

      // Create the task
      const taskData = {
        leadId: newTask.leadId,
        assignedTo: assignedTo,
        taskType: newTask.taskType,
        title: newTask.title,
        description: newTask.description || '',
        dueDate: dueDateStr,
        dueTime: dueTimeStr,
        priority: newTask.priority,
        status: 'Pending' as const
      };

      const created = await createTask(taskData);

      if (created) {
        if (!selectedLead.assignedTo || selectedLead.assignedTo !== assignedTo) {
          try {
            await updateLead(selectedLead.id, { assignedTo });
          } catch (assignError) {
            console.error('Error assigning lead during task creation:', assignError);
          }
        }

        setToast({ message: 'Task scheduled successfully.', type: 'success' });
        setShowCreateModal(false);
        setNewTask({
          leadId: '',
          taskType: 'Call',
          title: '',
          description: '',
          scheduledAt: '',
          dueAt: '',
          priority: 'Medium',
          agentId: '',
          notes: ''
        });
        setSelectedLeadOption(null);
      } else {
        setToast({ message: 'Failed to create task. Please try again.', type: 'error' });
      }
    } catch (err) {
      console.error('Error creating task:', err);
      setToast({ message: 'Failed to create task. Please try again.', type: 'error' });
    } finally {
      setIsSaving(false);
    }
  };

  const handleUpdateTask = () => {
    console.log('Update task:', selectedTask);
    setShowEditModal(false);
    setSelectedTask(null);
  };

  const handleConfirmDelete = () => {
    console.log('Delete task:', selectedTask?.id);
    setShowDeleteModal(false);
    setSelectedTask(null);
  };

  const formatDateTime = (dateString: string) => {
    return new Date(dateString).toLocaleString('en-GB', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getTaskStats = () => {
    const today = new Date().toISOString().split('T')[0];
    const todayTasks = diaryTasks.filter(task => 
      task.scheduledAt.startsWith(today)
    );
    
    return {
      total: diaryTasks.length,
      today: todayTasks.length,
      completed: diaryTasks.filter(t => t.status === 'Completed').length,
      overdue: diaryTasks.filter(t => t.status === 'Overdue').length,
      scheduled: diaryTasks.filter(t => t.status === 'Scheduled').length,
      inProgress: diaryTasks.filter(t => t.status === 'In Progress').length
    };
  };

  const stats = getTaskStats();

  return (
    <div className="space-y-6">
      {toast && (
        <div
          className={`fixed top-4 right-4 z-50 flex items-center gap-2 px-4 py-3 rounded-lg shadow-lg ${
            toast.type === 'success' ? 'bg-green-500 text-white' : 'bg-red-500 text-white'
          }`}
        >
          <span>{toast.message}</span>
        </div>
      )}
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Diary & Tasks</h1>
          <p className="text-gray-600">Manage your daily tasks and schedule</p>
        </div>
        <div className="flex space-x-3">
          <button 
            className="btn-secondary flex items-center space-x-2"
            onClick={() => console.log('Switch to calendar view')}
          >
            <Calendar className="h-5 w-5" />
            <span>Calendar View</span>
          </button>
          <button 
            className="btn-primary flex items-center space-x-2"
            onClick={() => setShowCreateModal(true)}
          >
            <Plus className="h-5 w-5" />
            <span>New Task</span>
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
        <div className="card">
          <div className="flex items-center">
            <div className="p-3 rounded-lg bg-blue-500">
              <Calendar className="h-6 w-6 text-white" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600">Total Tasks</p>
              <p className="text-2xl font-bold text-gray-900">{stats.total}</p>
            </div>
          </div>
        </div>
        <div className="card">
          <div className="flex items-center">
            <div className="p-3 rounded-lg bg-green-500">
              <CheckCircle className="h-6 w-6 text-white" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600">Completed</p>
              <p className="text-2xl font-bold text-gray-900">{stats.completed}</p>
            </div>
          </div>
        </div>
        <div className="card">
          <div className="flex items-center">
            <div className="p-3 rounded-lg bg-yellow-500">
              <Clock className="h-6 w-6 text-white" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600">Scheduled</p>
              <p className="text-2xl font-bold text-gray-900">{stats.scheduled}</p>
            </div>
          </div>
        </div>
        <div className="card">
          <div className="flex items-center">
            <div className="p-3 rounded-lg bg-purple-500">
              <Play className="h-6 w-6 text-white" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600">In Progress</p>
              <p className="text-2xl font-bold text-gray-900">{stats.inProgress}</p>
            </div>
          </div>
        </div>
        <div className="card">
          <div className="flex items-center">
            <div className="p-3 rounded-lg bg-red-500">
              <AlertCircle className="h-6 w-6 text-white" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600">Overdue</p>
              <p className="text-2xl font-bold text-gray-900">{stats.overdue}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="card">
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="flex-1">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
              <input
                type="text"
                placeholder="Search tasks by lead name or description..."
                className="input-field pl-10"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
          </div>
          <div className="flex gap-2">
            <select 
              className="input-field"
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value)}
            >
              <option value="All">All Status</option>
              <option value="Scheduled">Scheduled</option>
              <option value="In Progress">In Progress</option>
              <option value="Completed">Completed</option>
              <option value="Overdue">Overdue</option>
              <option value="Cancelled">Cancelled</option>
            </select>
            <select 
              className="input-field"
              value={filterType}
              onChange={(e) => setFilterType(e.target.value)}
            >
              <option value="All">All Types</option>
              <option value="Call">Call</option>
              <option value="SMS">SMS</option>
              <option value="Email">Email</option>
              <option value="Follow-up">Follow-up</option>
              <option value="Quote">Quote</option>
              <option value="Payment">Payment</option>
            </select>
            <select 
              className="input-field"
              value={filterAgent}
              onChange={(e) => setFilterAgent(e.target.value)}
            >
              <option value="All">All Agents</option>
              {agents.map(agent => (
                <option key={agent.id} value={agent.id}>
                  {agent.name}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Tasks List */}
      <div className="space-y-4">
        {filteredTasks.map((task) => (
          <div key={task.id} className="card">
            <div className="flex items-start justify-between">
              <div className="flex items-start space-x-4">
                <div className="flex-shrink-0">
                  <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center">
                    {getTypeIcon(task.taskType)}
                  </div>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center space-x-2 mb-1">
                    <h3 className="text-lg font-medium text-gray-900">{task.title}</h3>
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(task.status)}`}>
                      {task.status}
                    </span>
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getPriorityColor(task.priority)}`}>
                      {task.priority}
                    </span>
                    {task.autoGenerated && (
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                        Auto
                      </span>
                    )}
                  </div>
                  <p className="text-sm text-gray-600 mb-2">{task.description}</p>
                  <div className="flex items-center space-x-4 text-sm text-gray-500">
                    <div className="flex items-center space-x-1">
                      <User className="h-4 w-4" />
                      <span>{task.leadName}</span>
                    </div>
                    <div className="flex items-center space-x-1">
                      <Phone className="h-4 w-4" />
                      <span>{task.leadPhone}</span>
                    </div>
                    <div className="flex items-center space-x-1">
                      <Clock className="h-4 w-4" />
                      <span>{formatDateTime(task.scheduledAt)}</span>
                    </div>
                    {task.attemptNumber > 0 && (
                      <div className="flex items-center space-x-1">
                        <Target className="h-4 w-4" />
                        <span>{task.attemptNumber}/{task.maxAttempts} attempts</span>
                      </div>
                    )}
                  </div>
                  {task.notes && (
                    <div className="mt-2 text-sm text-gray-700 bg-gray-50 p-2 rounded">
                      {task.notes}
                    </div>
                  )}
                </div>
              </div>
              <div className="flex items-center space-x-2">
                {task.status === 'Scheduled' && (
                  <>
                    <button 
                      className="btn-primary text-sm"
                      onClick={() => handleStartTask(task)}
                    >
                      Start
                    </button>
                    <button 
                      className="btn-secondary text-sm"
                      onClick={() => handleRescheduleTask(task)}
                    >
                      Reschedule
                    </button>
                    <button 
                      className="btn-danger text-sm"
                      onClick={() => handleCancelTask(task)}
                    >
                      Cancel
                    </button>
                  </>
                )}
                {task.status === 'In Progress' && (
                  <button 
                    className="btn-success text-sm"
                    onClick={() => handleCompleteTask(task)}
                  >
                    Complete
                  </button>
                )}
                {task.status === 'Completed' && (
                  <div className="flex items-center space-x-1 text-green-600">
                    <CheckCircle className="h-4 w-4" />
                    <span className="text-sm">Completed</span>
                  </div>
                )}
                {task.status === 'Overdue' && (
                  <div className="flex items-center space-x-1 text-red-600">
                    <AlertCircle className="h-4 w-4" />
                    <span className="text-sm">Overdue</span>
                  </div>
                )}
                <div className="flex items-center space-x-2 ml-4">
                  <button 
                    className="text-gray-400 hover:text-gray-600" 
                    title="Edit Task"
                    onClick={() => handleEditTask(task)}
                  >
                    <Edit className="h-4 w-4" />
                  </button>
                  <button 
                    className="text-gray-400 hover:text-red-600" 
                    title="Delete Task"
                    onClick={() => handleDeleteTask(task)}
                  >
                    <Archive className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Create Task Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4 backdrop-blur-sm">
          <div className="bg-white rounded-lg w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="p-6 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-gray-900">Create New Task</h3>
                <button
                  onClick={() => {
                    setShowCreateModal(false);
                    setNewTask({
                      leadId: '',
                      taskType: 'Call',
                      title: '',
                      description: '',
                      scheduledAt: '',
                      dueAt: '',
                      priority: 'Medium',
                      agentId: '',
                      notes: ''
                    });
                    setLeadSearchTerm('');
                    setShowLeadDropdown(false);
                  }}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>
            </div>
            <div className="p-6 space-y-4">
              {/* Lead Selection */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Select Lead *
                </label>
                {isLoadingLeads ? (
                  <div className="flex items-center space-x-2 text-sm text-gray-500">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span>Loading leads...</span>
                  </div>
                ) : (
                  <div className="relative">
                    <div className="relative">
                      <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                      <input
                        type="text"
                        className="input-field pl-10"
                        placeholder="Search leads by name, email, or phone..."
                        value={leadSearchTerm}
                        onChange={(e) => {
                          setLeadSearchTerm(e.target.value);
                          setShowLeadDropdown(true);
                        }}
                        onFocus={() => setShowLeadDropdown(true)}
                        onClick={() => setShowLeadDropdown(true)}
                      />
                    </div>
                    {showLeadDropdown && leads.length > 0 && (
                      <>
                        <div
                          className="fixed inset-0 z-10"
                          onClick={() => setShowLeadDropdown(false)}
                        />
                        <div className="absolute z-20 w-full mt-1 bg-white border border-gray-300 rounded-lg shadow-lg max-h-60 overflow-y-auto">
                          {filteredLeads.length === 0 && debouncedLeadSearchTerm ? (
                                <div className="p-4 text-center text-sm text-gray-500">
                              No leads found matching "{debouncedLeadSearchTerm}"
                                  <div className="text-xs text-gray-400 mt-1">
                                    Try a different search term
                                  </div>
                                </div>
                          ) : filteredLeads.length === 0 ? (
                                <div className="p-4 text-center text-sm text-gray-500">
                                  No leads available
                                </div>
                          ) : (
                              <>
                              {debouncedLeadSearchTerm && (
                                  <div className="px-4 py-2 bg-gray-50 border-b border-gray-200 text-xs text-gray-600">
                                    Showing {filteredLeads.length} of {leads.length} lead(s)
                                  </div>
                                )}
                                {filteredLeads.map(lead => (
                                  <button
                                    key={lead.id}
                                    type="button"
                                    className="w-full text-left px-4 py-3 hover:bg-blue-50 border-b border-gray-100 last:border-b-0 transition-colors"
                                    onClick={() => {
                                      setSelectedLeadOption(lead);
                                      setNewTask({
                                        ...newTask,
                                        leadId: lead.id,
                                        agentId: lead.assignedTo || newTask.agentId
                                      });
                                      setLeadSearchTerm(lead.name);
                                      setShowLeadDropdown(false);
                                    }}
                                  >
                                    <div className="flex items-center justify-between">
                                      <div className="flex-1 min-w-0">
                                        <div className="font-medium text-gray-900 truncate">
                                          {lead.name || 'Unnamed Lead'}
                                        </div>
                                        {lead.email && (
                                          <div className="text-sm text-gray-500 truncate">
                                            {lead.email}
                                          </div>
                                        )}
                                        <div className="text-xs text-gray-400 mt-1 flex items-center gap-2 flex-wrap">
                                          {lead.phone && <span>{lead.phone}</span>}
                                          {lead.assignedTo && (
                                            <span>
                                              • Assigned to: {lead.assignedToName || lead.assignedTo}
                                            </span>
                                          )}
                                          {lead.stage && (
                                            <span>• Stage: {lead.stage}</span>
                                          )}
                                        </div>
                                      </div>
                                      {newTask.leadId === lead.id && (
                                        <CheckCircle className="h-5 w-5 text-green-600 flex-shrink-0 ml-2" />
                                      )}
                                    </div>
                                  </button>
                                ))}
                              </>
                            )}
                        </div>
                      </>
                    )}
                    {showLeadDropdown && leads.length === 0 && !isLoadingLeads && (
                      <>
                        <div
                          className="fixed inset-0 z-10"
                          onClick={() => setShowLeadDropdown(false)}
                        />
                        <div className="absolute z-20 w-full mt-1 bg-white border border-gray-300 rounded-lg shadow-lg p-4">
                          <div className="text-sm text-gray-500 text-center">
                            {user?.role === 'Agent' 
                              ? 'You don\'t have any assigned leads. Please contact your manager to get leads assigned.' 
                              : 'No leads available. Create a lead first in the Lead Management page.'}
                          </div>
                        </div>
                      </>
                    )}
                  </div>
                )}
                {!isLoadingLeads && leads.length === 0 && (
                  <p className="text-sm text-gray-500 mt-1">
                    No leads available. {user?.role === 'Agent' ? 'You don\'t have any assigned leads.' : 'Create a lead first.'}
                  </p>
                )}
                {newTask.leadId && !showLeadDropdown && (() => {
                  const selectedLead = selectedLeadOption || leads.find(l => l.id === newTask.leadId);
                  if (selectedLead) {
                    return (
                      <div className="mt-2 p-2 bg-blue-50 rounded-lg border border-blue-200">
                        <div className="flex items-center justify-between">
                          <div className="flex-1">
                            <div className="text-sm font-medium text-gray-900">
                              Selected: {selectedLead.name}
                            </div>
                            <div className="text-xs text-gray-600 mt-1">
                              {selectedLead.email} • {selectedLead.phone}
                            </div>
                          </div>
                          <button
                            type="button"
                            onClick={() => {
                              setNewTask({...newTask, leadId: ''});
                              setLeadSearchTerm('');
                              setSelectedLeadOption(null);
                            }}
                            className="text-gray-400 hover:text-gray-600"
                          >
                            <X className="h-4 w-4" />
                          </button>
                        </div>
                      </div>
                    );
                  }
                  return null;
                })()}
              </div>


              {/* Task Type */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Task Type *
                </label>
                <select
                  className="input-field"
                  value={newTask.taskType}
                  onChange={(e) => setNewTask({...newTask, taskType: e.target.value as any})}
                  required
                >
                  <option value="Call">Call</option>
                  <option value="SMS">SMS</option>
                  <option value="Email">Email</option>
                  <option value="Follow-up">Follow-up</option>
                  <option value="Quote">Quote</option>
                  <option value="Payment">Payment</option>
                </select>
              </div>

              {/* Task Title */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Task Title *
                </label>
                <input 
                  type="text" 
                  className="input-field"
                  placeholder="e.g., Initial Contact Call, Send Quote, Follow-up Email"
                  value={newTask.title}
                  onChange={(e) => setNewTask({...newTask, title: e.target.value})}
                  required
                />
              </div>

              {/* Description */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Description
                </label>
                <textarea 
                  className="input-field"
                  rows={3}
                  placeholder="Additional details about this task..."
                  value={newTask.description}
                  onChange={(e) => setNewTask({...newTask, description: e.target.value})}
                />
              </div>

              {/* Date and Time */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Scheduled Date & Time *
                  </label>
                  <input 
                    type="datetime-local" 
                    className="input-field"
                    value={newTask.scheduledAt}
                    onChange={(e) => {
                      setNewTask({
                        ...newTask,
                        scheduledAt: e.target.value,
                        dueAt: e.target.value || newTask.dueAt
                      });
                    }}
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Due Date & Time
                  </label>
                  <input
                    type="datetime-local"
                    className="input-field"
                    value={newTask.dueAt}
                    onChange={(e) => setNewTask({...newTask, dueAt: e.target.value})}
                  />
                </div>
              </div>

              {/* Priority and Assignment */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Priority *
                  </label>
                  <select
                    className="input-field"
                    value={newTask.priority}
                    onChange={(e) => setNewTask({...newTask, priority: e.target.value as any})}
                    required
                  >
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                  </select>
                </div>
                {(user?.role === 'Admin' || user?.role === 'Manager') && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Assign To
                    </label>
                    <select
                      className="input-field"
                      value={newTask.agentId}
                      onChange={(e) => setNewTask({...newTask, agentId: e.target.value})}
                    >
                      <option value="">Auto-assign (use lead's assigned agent)</option>
                      {agents.filter(a => a.role === 'Agent').map(agent => (
                        <option key={agent.id} value={agent.id}>
                          {agent.name}
                        </option>
                      ))}
                    </select>
              </div>
                )}
            </div>

              {/* Notes */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Notes (Optional)
                </label>
                <textarea
                  className="input-field"
                  rows={2}
                  placeholder="Any additional notes or reminders..."
                  value={newTask.notes}
                  onChange={(e) => setNewTask({...newTask, notes: e.target.value})}
                />
              </div>
            </div>
            <div className="p-6 border-t border-gray-200 flex justify-end space-x-3">
              <button 
                className="btn-secondary"
                onClick={() => {
                  setShowCreateModal(false);
                  setNewTask({
                    leadId: '',
                    taskType: 'Call',
                    title: '',
                    description: '',
                    scheduledAt: '',
                    dueAt: '',
                    priority: 'Medium',
                    agentId: '',
                    notes: ''
                  });
                  setLeadSearchTerm('');
                  setShowLeadDropdown(false);
                }}
                disabled={isSaving}
              >
                Cancel
              </button>
              <button 
                className="btn-primary"
                onClick={handleSaveTask}
                disabled={isSaving || !newTask.leadId || !newTask.title || !newTask.scheduledAt}
              >
                {isSaving ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin inline mr-2" />
                    Creating...
                  </>
                ) : (
                  'Create Task'
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Edit Task Modal */}
      {showEditModal && selectedTask && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">Edit Task</h3>
              <button 
                className="text-gray-400 hover:text-gray-600"
                onClick={() => setShowEditModal(false)}
              >
                <X className="h-6 w-6" />
              </button>
            </div>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Task Title</label>
                <input
                  type="text"
                  className="input-field"
                  defaultValue={selectedTask.title}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Description</label>
                <textarea
                  className="input-field"
                  rows={3}
                  defaultValue={selectedTask.description}
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Priority</label>
                  <select className="input-field" defaultValue={selectedTask.priority}>
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Status</label>
                  <select className="input-field" defaultValue={selectedTask.status}>
                    <option value="Scheduled">Scheduled</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Completed">Completed</option>
                    <option value="Cancelled">Cancelled</option>
                  </select>
                </div>
              </div>
            </div>
            
            <div className="flex justify-end space-x-3 mt-6">
              <button 
                className="btn-secondary"
                onClick={() => setShowEditModal(false)}
              >
                Cancel
              </button>
              <button 
                className="btn-primary"
                onClick={handleUpdateTask}
              >
                Update Task
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Task Modal */}
      {showDeleteModal && selectedTask && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">Delete Task</h3>
              <button 
                className="text-gray-400 hover:text-gray-600"
                onClick={() => setShowDeleteModal(false)}
              >
                <X className="h-6 w-6" />
              </button>
            </div>
            
            <div className="mb-6">
              <p className="text-gray-600 mb-4">
                Are you sure you want to delete the task "{selectedTask.title}"?
              </p>
              <div className="bg-red-50 border border-red-200 rounded-lg p-3">
                <p className="text-sm text-red-800">
                  <strong>Warning:</strong> This action cannot be undone. The task will be permanently removed.
                </p>
              </div>
            </div>
            
            <div className="flex justify-end space-x-3">
              <button 
                className="btn-secondary"
                onClick={() => setShowDeleteModal(false)}
              >
                Cancel
              </button>
              <button 
                className="btn-danger"
                onClick={handleConfirmDelete}
              >
                Delete Task
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
