import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { CheckCircle, Loader2, FileText } from 'lucide-react';

export const PaymentSuccess: React.FC = () => {
  const { token } = useParams<{ token: string }>();
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Payment is completed
    // The instruction form token should be generated by the Stripe webhook
    // We'll show a loading state briefly to allow webhook processing
    if (token) {
      // Set a timeout to allow webhook processing (typically takes 1-2 seconds)
      const timer = setTimeout(() => {
        setIsLoading(false);
      }, 2000);
      
      return () => clearTimeout(timer);
    } else {
      setIsLoading(false);
    }
  }, [token]);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin text-green-600 mx-auto mb-4" />
          <p className="text-gray-600">Processing your payment...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-2xl mx-auto">
        <div className="bg-white rounded-lg shadow-lg overflow-hidden">
          {/* Header */}
          <div className="bg-gradient-to-r from-green-600 to-green-700 px-6 py-8 text-white">
            <div className="flex items-center space-x-3 mb-2">
              <CheckCircle className="h-8 w-8" />
              <h1 className="text-3xl font-bold">Payment Successful!</h1>
            </div>
            <p className="text-green-100">
              Thank you for your payment. Your transaction has been processed successfully.
            </p>
          </div>

          {/* Content */}
          <div className="p-6 space-y-6">
            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <div className="flex items-start space-x-3">
                <CheckCircle className="h-6 w-6 text-green-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h3 className="text-lg font-semibold text-green-900 mb-1">
                    Payment Confirmed
                  </h3>
                  <p className="text-sm text-green-700">
                    Your payment has been received and processed. A confirmation email has been sent to you.
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-r-lg">
              <h2 className="text-lg font-semibold text-gray-900 mb-2">Next Steps</h2>
              <ol className="list-decimal list-inside space-y-2 text-gray-700">
                <li>You'll receive an email shortly with a link to complete your instruction form</li>
                <li>Complete the instruction form with your details</li>
                <li>Our team will begin processing your conveyancing once all information is received</li>
              </ol>
            </div>

            <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center">
              <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-gray-900 mb-2">
                Instruction Form Coming Soon
              </h3>
              <p className="text-sm text-gray-600 mb-4">
                Your payment has been confirmed! You'll receive an email shortly with a link to complete your instruction form.
              </p>
              <p className="text-xs text-gray-500">
                This typically takes just a few moments. Please check your email inbox.
              </p>
            </div>

            <div className="border-t pt-6">
              <h3 className="text-sm font-semibold text-gray-900 mb-2">What happens next?</h3>
              <ul className="space-y-2 text-sm text-gray-600">
                <li className="flex items-start">
                  <CheckCircle className="h-5 w-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" />
                  <span>Payment received and confirmed</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="h-5 w-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" />
                  <span>Instruction form link sent to your email</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="h-5 w-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" />
                  <span>Complete the instruction form with your details</span>
                </li>
                <li className="flex items-start">
                  <CheckCircle className="h-5 w-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" />
                  <span>Our team begins processing your conveyancing</span>
                </li>
              </ul>
            </div>

            <div className="bg-gray-50 rounded-lg p-4 text-sm text-gray-600">
              <p className="font-medium text-gray-900 mb-1">Need Help?</p>
              <p>
                If you have any questions about your payment or the next steps, please don't hesitate to contact us. 
                Our team is here to assist you throughout the process.
              </p>
            </div>

            <div className="flex justify-center pt-4">
              <button
                onClick={() => navigate('/')}
                className="px-6 py-2 text-gray-600 hover:text-gray-900 font-medium"
              >
                Return to Homepage
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

